name: Play

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL cần test (ví dụ https://example.com)'
        required: true
        default: 'https://example.com'
      duration:
        description: 'Thời gian test (giây)'
        required: true
        default: '45'
      concurrency:
        description: 'Số tab song song trong mỗi job (MAX_TAB)'
        required: true
        default: '2'
      req_per_loop:
        description: 'Số request/giây mỗi tab (MAX_RPS)'
        required: true
        default: '10'

jobs:
  flood:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,
                  17,18,19,20,21,22,23,24,25,26,27,28,29,30,
                  31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,
                  49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,
                  67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,
                  85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,
                  101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,
                  117,118,119,120,121,122,123,124,125,126,127,128]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: |
          pip install playwright 
          playwright install chromium

      - name: Run Flood
        env:
          TARGET_URL: ${{ inputs.target_url }}
          DURATION: ${{ inputs.duration }}
          MAX_TAB: ${{ inputs.concurrency }}
          MAX_RPS: ${{ inputs.req_per_loop }}
        run: python ply.py
